### PR TITLE
Handle an empty exclude-folders action option

### PR DESCRIPTION
**Pull request by allenporter**
Restructure how command line flags are handled by appending commands when
they are present and specified to avoid passing an empty string --exclude-folders which excluded everything.

Fixed issue #14

### CODE REVIEW

**Comment by allenporter** [comment]
For what it is worth, I am not a bash expert so I'm not sure if this is the best approach.  While I was addressing this, it seemed a little easier to follow and more future proof to use separate variables for the flags rather than rewriting the input variables.

**Comment by bjw-s** [comment]
In general I would say the change looks good. The only thing I wonder about is the following two faults that a ShellCheck run gave me:
- https://github.com/koalaman/shellcheck/wiki/SC3024
- line 11: https://github.com/koalaman/shellcheck/wiki/SC2236

The second one should be a quick fix, the first one might be as simple as changing the shebang to Bash, but I'm not sure if Bash is included so that would require some testing I guess :-)

**Comment by bjw-s** [comment]
I've added a ShellCheck linting workflow, that way we'll get triggered somewhat sooner :)

**Comment by allenporter** [comment]
> In general I would say the change looks good. The only thing I wonder about is the following two faults that a ShellCheck run gave me:
> 
> * https://github.com/koalaman/shellcheck/wiki/SC3024
> * line 11: https://github.com/koalaman/shellcheck/wiki/SC2236
> 
> The second one should be a quick fix, the first one might be as simple as changing the shebang to Bash, but I'm not sure if Bash is included so that would require some testing I guess :-)

I've fixed this and converted `entrypoint.sh` to bash. I realized this was bash syntax/features being used with sh script, and I was testing using bash only and missed this.

**Review by bjw-s — APPROVED** [review]

**Pull request merged**
