### PR TITLE
Support overlays when adding annotations to HelmReleases

### PR DESCRIPTION
**Pull request by allenporter**
Add support for overlays, by invoking `kustomize build` on the `Kustomization`s in the repository.

The basic workflow of the script is similar to before in that it does multiple passes. The first pass tracks `HelmRepository` chart urls and `HelmRelease` chart specs that reference the repository.  The second pass updates the `HelmRelease` with an annotation of the chart url.  The difference is now that it works with a partially specified `HelmRelease` since the chart spec can come from the fully built version via kustomize output.

Some caveats where I think feedback would be helpful:
- This assumes that repos using this action are using flux with `Kustomization`s next to the `HelmRelease`s which I think is a save bet.
- The docker image needs to be updated with a curl command to fetch `kustomize`
- The `kustomize` version itself is not vesioned.

### CODE REVIEW

**Comment by allenporter** [comment]
Example output for the test directory:
```
$ ./renovate.py --cluster-path=tests
2021-03-23 23:31:48 Renovate Helm Releases INFO     Discovered HelmRelease 'example/ingress-nginx-3' in tests/kustomizations/overlay
2021-03-23 23:31:49 Renovate Helm Releases INFO     Discovered HelmRelease 'example/ingress-nginx-3' in tests/kustomizations/base
2021-03-23 23:31:50 Renovate Helm Releases INFO     Discovered HelmRepository 'flux-system/ingress-nginx-charts' chart url 'https://kubernetes.github.io/ingress-nginx'
2021-03-23 23:31:50 Renovate Helm Releases INFO     Discovered HelmRepository 'flux-system/k8s-at-home-charts' chart url 'https://k8s-at-home.com/charts/'
2021-03-23 23:31:50 Renovate Helm Releases INFO     Discovered HelmRepository 'flux-system/traefik-charts' chart url 'https://helm.traefik.io/traefik'
2021-03-23 23:31:51 Renovate Helm Releases INFO     Discovered HelmRelease 'cert-manager/cert-manager' in tests/helm-releases
2021-03-23 23:31:51 Renovate Helm Releases INFO     Discovered HelmRelease 'default/ingress-nginx-1' in tests/helm-releases
2021-03-23 23:31:51 Renovate Helm Releases INFO     Discovered HelmRelease 'default/ingress-nginx-2' in tests/helm-releases
2021-03-23 23:31:51 Renovate Helm Releases INFO     Discovered HelmRelease 'default/blocky' in tests/helm-releases
2021-03-23 23:31:52 Renovate Helm Releases INFO     Discovered HelmRelease 'default/blocky' in tests/helm-releases/blocky
2021-03-23 23:31:52 Renovate Helm Releases INFO     Discovered HelmRelease 'default/ingress-nginx-2' in tests/helm-releases/ingress-nginx-2
2021-03-23 23:31:53 Renovate Helm Releases INFO     Discovered HelmRelease 'cert-manager/cert-manager' in tests/helm-releases/cert-manager
2021-03-23 23:31:54 Renovate Helm Releases INFO     Discovered HelmRelease 'default/ingress-nginx-1' in tests/helm-releases/ingress-nginx-1
2021-03-23 23:31:54 Renovate Helm Releases INFO     Updating 'flux-system/ingress-nginx-charts' renovate annotations in 'tests/kustomizations/overlay/ingress-nginix-3-values.yaml' with 'https://kubernetes.github.io/ingress-nginx'
2021-03-23 23:31:54 Renovate Helm Releases INFO     Updating 'flux-system/k8s-at-home-charts' renovate annotations in 'tests/helm-releases/blocky/helm-release.yaml' with 'https://k8s-at-home.com/charts/'
2021-03-23 23:31:54 Renovate Helm Releases INFO     Updating 'flux-system/ingress-nginx-charts' renovate annotations in 'tests/helm-releases/ingress-nginx-2/helm-release.yaml' with 'https://kubernetes.github.io/ingress-nginx'
2021-03-23 23:31:54 Renovate Helm Releases INFO     Updating 'flux-system/ingress-nginx-charts' renovate annotations in 'tests/helm-releases/ingress-nginx-1/helm-release.yaml' with 'https://kubernetes.github.io/ingress-nginx'
```

**Comment by allenporter** [comment]
One thought here is I can break this into a smaller set of PRs if that helps.

Or move the kustomize wrapper into a pypi library either now or at some point. I'm thinking about using this for more and sharing code with tests invoked from other github actions e.g.
https://github.com/allenporter/k8s-gitops/blob/main/tests/kustomize_validation_test.py

**Comment by onedr0p** [comment]
One PR is fine, and splitting the kustomize stuff in a py package is up to you. I don't know how helpful that will be tbh

**Comment by allenporter** [comment]
OK -- i'm going to leave as is for now. This is ready for review.

**Comment by onedr0p** [comment]
@allenporter I notice your changes makes the script take much longer to run. This might be an issue running against a large cluster folder.

Is there any optimizations you can do to speed it up?

```sh
time python3 renovate.py --cluster-path ./tests/
```

Before:

```
________________________________________________________
Executed in   98.89 millis    fish           external
   usr time   75.56 millis   98.00 micros   75.46 millis
   sys time   19.27 millis  768.00 micros   18.50 millis
```

After:

```
________________________________________________________
Executed in    5.97 secs    fish           external
   usr time    6.39 secs  107.00 micros    6.39 secs
   sys time    0.35 secs  803.00 micros    0.35 secs
```

**Comment by onedr0p** [comment]
I am thinking it might be possible to add a `metadata.label` to the base and overlay HelmReleases to hopefully work within the confines of our current approach e.g.

Base:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-3
  namespace: example
  labels:
    renovate.helm.release: base
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
```

Overlay:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-3
  namespace: example
  labels:
    renovate.helm.release: overlay
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.23.0
  values:
    controller:
      ingressClass: class-1
```

I would think something like this  might work well and possibly remove the need for kustomize?

**Comment by allenporter** [comment]
Yes it's definitely slow as it's forking a subproc for every file relevant file.  I can think about this more and take a moment to understand your suggestions.  Thanks for taking a look.

My other thought was to try and understand the root kustomization instead of picking up files randomly.

**Comment by allenporter** [comment]
I found a simpler approach that makes `kustomize build` not necessary, but just assuming that from an overlay `HelmRelease` we can can look up the `HelmRepository` from any other `HelmRelease` that happens to have the same name. I think this is a safe enough assumption, but curious what you think. This logs a warning if that assumption is broken.

This means that the `kustomize` dependency is not necessary, nor is it necessary to add additional `kustomzation.yaml` files.  However, I found another interesting command that makes `kustomize` perhaps still useful to invoke here. You can use `kustomize cfg grep` to spit out all the yaml files for an associated kind, which I played around with for finding all `HelmRelease` and `HelmRepository` objects in the cluster. I'd love to get your opinion on if this is worthwhile, otherwise I can revert it back to the old way.

I removed all `kustomization.yaml` files since they are not necessary, but I left them in the directory with an overlay even though technically they aren't needed, just because it seems to make more sense as an example.

Timing for the test repo:
```
$ time ./renovate.py --cluster-path tests 
real	0m0.201s
user	0m0.156s
sys	0m0.055s
```

Timing for a larger cluster:
```
$ time ./renovate.py --cluster-path ~/k8s-gitops/
real	0m0.401s
user	0m0.362s
sys	0m0.103s
```

Let me know what you think.

**Comment by onedr0p** [comment]
Looking better! IMO if you can do it without kustomize and there's no significant time to run the script, I'd say remove it.

Currently there's no easy way to integrate renovate here too release new versions of the action, so managing updates to kustomize would be a little annoying.

**Comment by allenporter** [comment]
This is ready for another look. I reverted the dependencies on kustomize and decided just to simplify the test cases down into the bare minimum. I left in the *style* cleanups since i think this structure is helpful given the multiple passes.

**Comment by onedr0p** [comment]
Thanks! I'll have time tomorrow afternoon to review.

**Comment by onedr0p** [comment]
Merging this, looks to work just fine. Thanks @allenporter !

**Comment by onedr0p** [comment]
@all-contributors add @allenporter  for code

**Pull request merged**
